version: '3.8'
services:
  pybot:
    build:
      context: .
      dockerfile: Dockerfile-pybot
    restart: always
    ports:
      - 8081:80
    volumes:
      - .:/app
    container_name: pybot-container
